#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const contract=JSON.parse(fs.readFileSync(path.join(ROOT,'data/release/accepted_output_freeze_contract.json'),'utf8'));
const registryPath=path.join(ROOT,contract.frozen_registry); const cacheDir=path.join(ROOT,contract.cache_dir); const scopePath=path.join(ROOT,contract.active_mutation_scope);
const hash=(b)=>crypto.createHash('sha256').update(b).digest('hex');
const normalizeRoute=(r)=>{r=String(r||'').trim();if(!r)return '';if(!r.startsWith('/'))r='/'+r;return r==='/'?'/':r.replace(/\/$/,'');};
const getBy=(o,key)=>String(key||'').split('.').filter(Boolean).reduce((v,k)=>v?.[k],o);
function resolveRoute(route){for(const pat of contract.route_resolution||[]){const rel=pat.replace('{route}',normalizeRoute(route).replace(/^\//,''));const abs=path.join(ROOT,rel);if(fs.existsSync(abs)&&fs.statSync(abs).isFile())return rel;}return null;}
function acceptedRecords(){const src=JSON.parse(fs.readFileSync(path.join(ROOT,contract.source_registry),'utf8'));const rows=getBy(src,contract.source_array)||[];const statuses=new Set(contract.accepted_statuses||[]);const records=rows.filter(r=>statuses.has(r[contract.status_field])).map(r=>({route:normalizeRoute(r[contract.route_field]),source:r})).filter(r=>r.route);for(const extra of contract.extra_static_files||[])records.push({route:normalizeRoute(extra.route),source:{__extra_file:extra.file}});return records;}
function loadRegistry(){return fs.existsSync(registryPath)?JSON.parse(fs.readFileSync(registryPath,'utf8')):{schema_version:'1.0',generated_at:null,count:0,pages:[]};}
function scopeRoutes(){if(!fs.existsSync(scopePath))return new Set();const d=JSON.parse(fs.readFileSync(scopePath,'utf8'));return new Set((d.routes||[]).map(normalizeRoute));}
function writeRegistry(pages){const out={schema_version:'1.0',generated_at:'2026-07-24T00:00:00.000Z',count:pages.length,pages:pages.sort((a,b)=>a.route.localeCompare(b.route))};fs.writeFileSync(registryPath,JSON.stringify(out,null,2)+'\n');return out;}
function freeze(){fs.mkdirSync(cacheDir,{recursive:true});const old=new Map(loadRegistry().pages.map(x=>[x.route,x]));const allowed=scopeRoutes();const unscoped=[];for(const [route,p] of old){const f=path.join(ROOT,p.rendered_file||'');if(!fs.existsSync(f))continue;const current=hash(fs.readFileSync(f));if(current!==p.accepted_sha256&&!allowed.has(normalizeRoute(route)))unscoped.push({route,rendered_file:p.rendered_file,before:p.accepted_sha256,after:current});}if(unscoped.length){console.error(JSON.stringify({error:'UNSCOPED_FROZEN_OUTPUT_DRIFT',count:unscoped.length,sample:unscoped.slice(0,20)},null,2));process.exit(1);}const pages=[];let created=0,unchanged=0,missing=0;for(const rec of acceptedRecords()){const file=rec.source?.__extra_file || resolveRoute(rec.route);if(!file){missing++;continue;}const raw=fs.readFileSync(path.join(ROOT,file));const accepted=hash(raw);const existing=old.get(rec.route);if(existing?.accepted_sha256===accepted&&existing.cache_file&&fs.existsSync(path.join(ROOT,existing.cache_file))){pages.push(existing);unchanged++;continue;}const gz=zlib.gzipSync(raw,{level:9,mtime:0});const cacheRel=`${contract.cache_dir}/${accepted}.html.gz`;const cacheAbs=path.join(ROOT,cacheRel);if(!fs.existsSync(cacheAbs))fs.writeFileSync(cacheAbs,gz);pages.push({route:rec.route,rendered_file:file,state:'FROZEN',accepted_sha256:accepted,cache_file:cacheRel,cache_sha256:hash(fs.readFileSync(cacheAbs)),accepted_at:'2026-07-24'});created++;}
 const keep=new Set(pages.map(p=>p.cache_file));for(const name of fs.readdirSync(cacheDir)){const rel=`${contract.cache_dir}/${name}`;if(!keep.has(rel)&&name.endsWith('.html.gz'))fs.rmSync(path.join(cacheDir,name),{force:true});}
 const out=writeRegistry(pages);console.log(JSON.stringify({command:'freeze',frozen:out.count,created_or_updated:created,unchanged,accepted_routes_without_resolved_html:missing},null,2));}
function restore(){const reg=loadRegistry();const thaw=scopeRoutes();let restored=0,skipped=0,missing=0;for(const p of reg.pages||[]){if(thaw.has(normalizeRoute(p.route))){skipped++;continue;}const cache=path.join(ROOT,p.cache_file||'');if(!fs.existsSync(cache)){missing++;continue;}const raw=zlib.gunzipSync(fs.readFileSync(cache));const out=path.join(ROOT,p.rendered_file);const current=fs.existsSync(out)?hash(fs.readFileSync(out)):null;if(current!==p.accepted_sha256){fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,raw);restored++;}}
 console.log(JSON.stringify({command:'restore',restored,transactionally_thawed:skipped,missing_cache:missing},null,2));if(missing)process.exit(1);}
function prepareScope(){const p=path.join(ROOT,contract.release_plan);const d=JSON.parse(fs.readFileSync(p,'utf8'));const rows=getBy(d,contract.release_plan_array)||[];const routes=[...new Set(rows.map(r=>normalizeRoute(r[contract.release_plan_route_field])).filter(Boolean))].sort();fs.writeFileSync(scopePath,JSON.stringify({schema_version:'1.0',generated_at:new Date().toISOString(),source:contract.release_plan,routes},null,2)+'\n');console.log(JSON.stringify({command:'prepare-scope',routes:routes.length},null,2));}
function clearScope(){fs.rmSync(scopePath,{force:true});console.log(JSON.stringify({command:'clear-scope',cleared:true},null,2));}
function status(){const reg=loadRegistry();const thaw=scopeRoutes();let drift=0,missing=0;for(const p of reg.pages||[]){const f=path.join(ROOT,p.rendered_file||'');if(!fs.existsSync(f)){missing++;continue;}if(!thaw.has(normalizeRoute(p.route))&&hash(fs.readFileSync(f))!==p.accepted_sha256)drift++;}console.log(JSON.stringify({command:'status',frozen:(reg.pages||[]).length,active_mutation_routes:thaw.size,unscoped_drift:drift,missing_rendered:missing},null,2));if(drift||missing)process.exit(1);}
const cmd=process.argv[2]||'status';({freeze,restore,status,'prepare-scope':prepareScope,'clear-scope':clearScope}[cmd]||(()=>{throw new Error(`Unknown command ${cmd}`)}))();
